MovieShop.MVC/MovieShop.MVC/Controllers/CastController.cs
using MovieShop.Entities;
using MovieShop.Sevices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieShop.MVC.Controllers
{
    public class CastController : Controller
    {
        private readonly ICastService _castService;

        public CastController()
        {
            _castService = new CastService();
        }
        // GET: Cast
        public ActionResult Index()
        {
            return View();
        }

        //cast/creaTE HTTP GET
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Cast cast) //(object in parameter), must pass with cshtml "name". ex: castname != name
        {
            _castService.AddCast(cast);
            return View();
        }

        //step 1: create a action method that returns empty view to enter cast info
    }
}

MovieShop.MVC/MovieShop.MVC/Controllers/GenresController.cs
using MovieShop.Services;
using MovieShop.Sevices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieShop.MVC.Controllers
{
    public class GenresController : Controller
    {
        IGenreService _genreService;
        // GET: Genres
        public GenresController(IGenreService genreService)
        {
            _genreService = genreService;
        }
        public PartialViewResult Index()
        {
            return PartialView("GenresView", _genreService.GetAllGenres().OrderBy(g => g.Name).ToList());
        }
    }
}

MovieShop.MVC/MovieShop.MVC/Controllers/HomeController.cs
using MovieShop.MVC.Filters;
using MovieShop.Sevices;
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieShop.MVC.Controllers
{
    [MovieShopExceptionFilter]
    public class HomeController : Controller
    {
        private readonly IMovieService _movieService;

        public HomeController(IMovieService movieService)
        {
            _movieService = movieService;
        }
        //[LogActionFilter]
        public ActionResult Index()
         {
            // get top revenue movies and show them in home page, 
            //use same movie card as you did for genres movies
            var movies = _movieService.GetTopGrossingMovies();
            return View(movies);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MovieShop.MVC/MovieShop.MVC/Controllers/MoviesController.cs
using System.Linq;
using System.Web.Mvc;
using MovieShop.Entities;
using MovieShop.Sevices;
// using X.PagedList;

namespace MovieShopMVC.Controllers
{
    //DI with Contructor Injection
    [RoutePrefix("movies")]
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;
        //MVC 5 requires Parameterless Constructor
        // For IMovieService movieService, we need to inject an implementation
        //we can pass any object/instance that implements IMovieService interface
        //In our project Movie Service class is implemetning IMovieService Interface
        //IOC should inject instance of  MovieService fro Constructor
        //.Net  Framework there are no buildt-in IOC, we need to download 3rd party IOC'S
        //Popular 3rd party IOC's like Ninject, Autofac, Unity etc
        //in .NET Core or ASP.NET Core Dependency Injection in builtin, no need 3rd party
        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }


        [HttpGet]
     
        public ActionResult Index()
            
        {
            // call service layer to get top 20 recenue movies
            //routing 
            //all url's always map to vies
            //ActionResult method needs to return View
            //every http request always go to controlelr first, then action methods needs to return to view
            var movies = _movieService.GetTopGrossingMovies(); //movie is a object model, is a list, but base type in the c#

            return View(movies);
        }



        //[Route("details/{id}")]
        public ActionResult Details(int id)
        {
            var movie = _movieService.GetMovieDetails(id);
            return View(movie);
        }

        [Route("genre/{genreId}")]
        public ActionResult Genre(int genreId)
        {
            var movies = _movieService.GetMoviesByGenre(genreId).OrderBy(m => m.Title).ToList();
            return View("MoviesByGenre", movies);
        }


        [HttpPost]
        [Route("create")]
        public ActionResult Create(Movie movie)
        {

            return View("Index");
        }

        //take genre id from url aand then call movie service to get the list of movies belong to the genre
        //return movies to the view and display as Imagetags insode the bootstrap card with image urls as 
        //posterUrl form Movie table column
        //create getMoviesByGenre(int genreId) inside IMovieService call Movies Repo to get movies of that gene
    }
}

MovieShop.MVC/MovieShop.MVC/Views/Cast/Create.cshtml
@model MovieShop.Entities.Cast

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cast</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TmdbUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TmdbUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TmdbUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfilePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProfilePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProfilePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MovieShop.MVC/MovieShop.MVC/Views/Cast/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

MovieShop.MVC/MovieShop.MVC/Views/Cast/oldCreate.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create Cast</h2>

<form method="post">
    Name: <input type="text" name="name" id="castname" value="" /><br/>
    Gender: <input type="text" name="gender" id="gender" value="" /><br />
    Tmdb Url: <input type="text" name="tmdbUrl" id="tmdbUrl" value="" /><br />
    Profile Path: <input type="text" name="profilePath" id="profilePath" value="" /><br />

<input type="submit" name="save" value="Save Cast" />

</form> 

MovieShop.MVC/MovieShop.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MovieShop.MVC/MovieShop.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MovieShop.MVC/MovieShop.MVC/Views/Home/Index.cshtml
@model List<MovieShop.Entities.Movie>
@{
    ViewBag.Title = "Home Page";
}
<h2>
    Top Revenue Movies
</h2>


<div class="rounded">
    <div class="container-fluid bg-light">
        <div class="row">
            @foreach (var movie in Model)
            {
                <div class="col-6 col-lg-3 col-sm-4 col-xl-2">
                    @Html.Partial("_MovieCard", movie)
                </div>
            }

        </div>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Revenue</th>
            <th scope="col">Date Released</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var movie in Model)
        {
            <tr>
                <td>@movie.Id</td>
                <td>@movie.Title</td>
                <td>@movie.Revenue</td>
                <td>
                    @if (movie.ReleaseDate != null)
                    {
                        @movie.ReleaseDate.Value.ToShortDateString()
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

MovieShop.MVC/MovieShop.MVC/Views/Movies/Create.cshtml
@model MovieShop.Entities.Movie

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <h3>Create Movie</h3>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Overview, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Overview, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Overview, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Tagline)
        <div class="col-md-10">
            @Html.EditorFor(model => model.Tagline, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Tagline, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Budget, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Budget, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Budget, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Revenue, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Revenue, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Revenue, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImdbUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ImdbUrl, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ImdbUrl, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TmdbUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TmdbUrl, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TmdbUrl, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PosterUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PosterUrl, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PosterUrl, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BackdropUrl, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BackdropUrl, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BackdropUrl, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OriginalLanguage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.OriginalLanguage, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.OriginalLanguage, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RunTime, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RunTime, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RunTime, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MovieShop.MVC/MovieShop.MVC/Views/Movies/Details.cshtml
@model MovieShop.Entities.Movie
@{
    ViewBag.Title = "Details";
}


<div class="bg-image" style="background-image: url(@Model.BackdropUrl)">

    <div class="row">
        <div class="col-md-3 offset-2">

            <!-- Movie Card row -->
            <div>
                <img src="@Model.PosterUrl" class="card-img-top" />
            </div>

        </div>
        <div class="col-md-4">
            <div class="row mt-2">
                <div class="col-12">
                    <h1 class="text-white">
                        @Model.Title
                    </h1>
                    <small class="text-muted"> @Model.Tagline </small>
                </div>

            </div>

            <div class="row">
                <div class="col-4 text-secondary font-weight-bold mt-2">
                    @Model.RunTime m | @Model.ReleaseDate.Value.Date.Year
                </div>
                <div class="col-8">

                    @foreach (var genre in Model.Genres)
                    {
                        <a href="@Url.Action("Genre", "Movies", new {genreId = genre.Id})"
                           class="badge badge-pill badge-dark ml-1">
                            @genre.Name
                        </a>
                    }
                </div>
            </div>

            <div class="row">
                <div class="col-4 mt-3">
                    <h4>
                        <span class="badge badge-warning">
                            @Model.Rating
                        </span>
                    </h4>
                </div>
            </div>

            <div class="row">
                <div class="col-12 text-light mt-2">
                    @Model.Overview
                </div>
            </div>
        </div>

        <div class="col-md-2 mt-4 offset-1">
            <ul class="list-group">
                <li class="list-group-item">


                </li>
                <li class="list-group-item">
                    <button type="button"
                            class="btn btn-outline-light btn-lg btn-block btn-sm">
                        <i class="far fa-edit mr-1"></i>
                        REVIEW
                    </button>
                </li>
                <li class="list-group-item">
                    <button type="button"
                            class="btn btn-outline-light btn-lg btn-block btn-sm">
                        <i class="fas fa-play mr-1"></i> TRAILER
                    </button>
                </li>

                <li class="list-group-item">
                    <button type="button" class="btn btn-light btn-lg btn-block btn-sm">
                        BUY @Model.Price
                    </button>

                    <button type="button" class="btn btn-light btn-lg btn-block btn-sm">
                        WATCH MOVIE
                    </button>
                </li>
            </ul>
        </div>

    </div>
</div>

MovieShop.MVC/MovieShop.MVC/Views/Movies/Index.cshtml
@model List<MovieShop.Entities.Movie>
@{
    ViewBag.Title = "Index";
}


<table class = "table">
    <tr>
        <td> Id   </td>
        <td> Title   </td>
        <td> Revenue   </td>
        <td> Budget   </td>
    </tr>

    <tbody>
        @foreach (var movie in Model) //razer index, Model represents view retrun 
        {
            <tr>
                <td>@movie.Id </td>
                <td>@movie.Title</td>
                <td>@movie.Revenue</td>
                <td>@movie.Budget</td>
            </tr>
        }
    </tbody>
</table>

MovieShop.MVC/MovieShop.MVC/Views/Movies/MoviesByGenre.cshtml
@model List<MovieShop.Entities.Movie>

@{
    ViewBag.Title = "Movies By Genre";
}

<div class="rounded">
    <div class="container-fluid bg-light">
        <div class="row">
            @foreach (var movie in Model)
            {
                <div class="col-6 col-lg-3 col-sm-4 col-xl-2">
                    @Html.Partial("_MovieCard", movie)
                </div>
            }

        </div>
    </div>
</div>

<table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Revenue</th>
                <th scope="col">Date Released</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var movie in Model)
            {
                <tr>
                    <td>@movie.Id</td>
                    <td>@movie.Title</td>
                    <td>@movie.Revenue</td>
                    <td>
                        @if (movie.ReleaseDate != null)
                        {
                            @movie.ReleaseDate.Value.ToShortDateString()
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>

MovieShop.MVC/MovieShop.MVC/Views/Shared/GenresView.cshtml
@model IEnumerable<MovieShop.Entities.Genre>

@foreach (var genre in Model)
{
    @Html.ActionLink(genre.Name, "Genre", "Movies", new { genreId = genre.Id }, new { @class = "dropdown-item" })
}

MovieShop.MVC/MovieShop.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top ">
        @Html.ActionLink("Movie Shop", "Index", "Home", new { @class = "navbar-brand" })

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item dropdown">
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @Html.ActionLink("Top Movies", "Genre", "Movies", "", new { @class = "dropbvdown-item" })
                    </div>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Genres
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @{ Html.RenderAction("Index", "Genres"); }
                    </div>
                </li>


                <li class="nav-item">
                    @Html.ActionLink("Login", "User", "SignIn", null, new { @class = "btn btn-outline-primary rounded-pill" })

                </li>
                <li class="nav-item ">
                    @Html.ActionLink("SignUp", "User", "SignUp", null, new { @class = "btn btn-primary rounded-pill" })

                </li>
                <li class="nav-item">
                    @Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link" })

                </li>
                <li class="nav-item">
                    @Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link" })
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search Movies" aria-label="Search">
                <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
            </form>

        </div>
    </nav>


    <div class="container-fluid mt-5 pt-4">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Movie Shop</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", false)
</body>
</html>

MovieShop.MVC/MovieShop.MVC/Views/Shared/_MovieCard.cshtml
@model MovieShop.Entities.Movie

<div class="card mb-4 shadow bg-light">


    <a href="@Url.Action("Details", "Movies", new {id = Model.Id})">
        <img src="@Url.Content(Model.PosterUrl)" class="img-fluid " />
    </a>

</div>